name = "customer-service-ai-platform"
main = "src/index_new.js"
compatibility_date = "2023-12-01"

[site]
bucket = "./public"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Vectorize binding for semantic search
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "support-agent-index"

# D1 Database binding for multi-tenant data
[[d1_databases]]
binding = "DB"
database_name = "customer_service_db"
database_id = "your-database-id-here"

# Durable Objects binding for chat sessions
[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSessionDO"]

# Environment variables
[vars]
JWT_SECRET = "replace-with-your-secret-in-production"
ALLOWED_ORIGINS = "*"

# Scheduled tasks (cron jobs)
[triggers]
crons = ["0 0 * * *"]  # Run daily at midnight to clean up expired sessions
